In [ ]:
#data encoding >> converting categorical data into numerical data
#Normal/OHE
#Label and ordinal encoding
#Target guided ordincal encoding

In [18]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OrdinalEncoder


In [2]:
df = pd.DataFrame({"status": ['married', 'single', 'seperated', 'single','married','seperated']})

In [3]:
df

status
0    married
1     single
2  seperated
3     single
4    married
5  seperated

In [4]:
encoder = OneHotEncoder()


In [10]:
encoder_df = pd.DataFrame(encoder.fit_transform(df[['status']]).toarray(), columns = encoder.get_feature_names_out())

In [11]:
encoder_df

status_married  status_seperated  status_single
0             1.0               0.0            0.0
1             0.0               0.0            1.0
2             0.0               1.0            0.0
3             0.0               0.0            1.0
4             1.0               0.0            0.0
5             0.0               1.0            0.0

In [12]:
pd.concat([df, encoder_df], axis = 1)

status  status_married  status_seperated  status_single
0    married             1.0               0.0            0.0
1     single             0.0               0.0            1.0
2  seperated             0.0               1.0            0.0
3     single             0.0               0.0            1.0
4    married             1.0               0.0            0.0
5  seperated             0.0               1.0            0.0

In [15]:
#label encoding
label_encoder = LabelEncoder()

In [16]:
label_encoder.fit_transform(df[['status']])

c:\Users\moksh\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 2, 1, 2, 0, 1])

In [21]:
#ordinal encoding 
#it is used when the data is ordinal in nature

df = pd.DataFrame ({'qualification' : ['high', 'medium', 'low', 'high', 'medium', 'low']})


In [22]:
encoder = OrdinalEncoder(categories = [['low', 'medium', 'high']])


In [23]:
encoder.fit_transform(df[['qualification']])

array([[2.],
       [1.],
       [0.],
       [2.],
       [1.],
       [0.]])

In [24]:
encoder.transform([['medium']])

c:\Users\moksh\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[1.]])

In [25]:
#target guided ordinal encoding
df = pd.DataFrame({'time':['lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner', 'lunch', 'breakfast', 'dinner'],
             'total_bill': [120, 130, 90, 125, 150, 190, 160, 180, 189]})


In [26]:
df

time  total_bill
0      lunch         120
1  breakfast         130
2     dinner          90
3      lunch         125
4  breakfast         150
5     dinner         190
6      lunch         160
7  breakfast         180
8     dinner         189

In [27]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()

In [28]:
df['time_encoded'] = df['time'].map(mean_price)

In [29]:
df

time  total_bill  time_encoded
0      lunch         120    135.000000
1  breakfast         130    153.333333
2     dinner          90    156.333333
3      lunch         125    135.000000
4  breakfast         150    153.333333
5     dinner         190    156.333333
6      lunch         160    135.000000
7  breakfast         180    153.333333
8     dinner         189    156.333333